from typing import Iterator, Protocol


class ChatProvider(Protocol):
    def complete(self, *, system: str, messages: list[dict], max_tokens: int = 1024) -> str: ...

    def complete_json(self, *, system: str, messages: list[dict], schema: dict, max_tokens: int = 1024) -> dict | None: ...

    def stream(self, *, system: str, messages: list[dict], max_tokens: int = 4096) -> Iterator[str]: ...


class EmbeddingProvider(Protocol):
    def embed_documents(self, texts: list[str]) -> list[list[float]]: ...

    def embed_query(self, text: str) -> list[float]: ...
